export const newState = [
  {
    code: "FC",
    name: "Abuja",
    lgas: ["Abuja", "Kwali", "Kuje", "Gwagwalada", "Bwari", "Abaji"],
    popular: ["Central "],
  },
  {
    code: "AB",
    name: "Abia",
    lgas: [
      "Aba North",
      "Aba South",
      "Arochukwu",
      "Bende",
      "Ikawuno",
      "Ikwuano",
      "Isiala-Ngwa North",
      "Isiala-Ngwa South",
      "Isuikwuato",
      "Umu Nneochi",
      "Obi Ngwa",
      "Obioma Ngwa",
      "Ohafia",
      "Ohaozara",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa West",
      "Ukwa East",
      "Umuahia North",
      "Umuahia South",
    ],
  },
  {
    code: "AD",
    name: "Adamawa",
    lgas: [
      "Demsa",
      "Fufore",
      "Ganye",
      "Girei",
      "Gombi",
      "Guyuk",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo-Belwa",
      "Michika",
      "Mubi-North",
      "Mubi-South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South",
    ],
  },
  {
    code: "AK",
    name: "AkwaIbom",
    lgas: [
      "Abak",
      "Eastern-Obolo",
      "Eket",
      "Esit-Eket",
      "Essien-Udim",
      "Etim-Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo-Asutan",
      "Ibiono-Ibom",
      "Ika",
      "Ikono",
      "Ikot-Abasi",
      "Ikot-Ekpene",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat-Enin",
      "Nsit-Atai",
      "Nsit-Ibom",
      "Nsit-Ubium",
      "Obot-Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Oruk Anam",
      "Udung-Uko",
      "Ukanafun",
      "Urue-Offong/Oruko",
      "Uruan",
      "Uyo",
    ],
  },
  {
    code: "AN",
    name: "Anambra",
    lgas: [
      "Aguata",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Awka North",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili-North",
      "Idemili-South",
      "Ihiala",
      "Njikoka",
      "Nnewi-North",
      "Nnewi-South",
      "Ogbaru",
      "Onitsha-North",
      "Onitsha-South",
      "Orumba-North",
      "Orumba-South",
    ],
  },
  {
    code: "BA",
    name: "Bauchi",
    lgas: [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas Gadau",
      "Jama'Are",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa-Balewa",
      "Toro",
      "Warji",
      "Zaki",
    ],
  },
  {
    code: "BY",
    name: "Bayelsa",
    lgas: [
      "Brass",
      "Ekeremor",
      "Kolokuma Opokuma",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern-Ijaw",
      "Yenagoa",
    ],
  },
  {
    code: "BE",
    name: "Benue",
    lgas: [
      "Ado",
      "Agatu",
      "Apa",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer-East",
      "Gwer-West",
      "Katsina-Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Otukpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya",
    ],
  },
  {
    code: "BO",
    name: "Borno",
    lgas: [
      "Abadam",
      "Askira-Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gubio",
      "Guzamala",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kala Balge",
      "Konduga",
      "Kukawa",
      "Kwaya-Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Marte",
      "Mobbar",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani",
    ],
  },
  {
    code: "CR",
    name: "CrossRiver",
    lgas: [
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar-Municipal",
      "Calabar-South",
      "Etung",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Yakurr",
      "Yala",
    ],
  },
  {
    code: "DE",
    name: "Delta",
    lgas: [
      "Aniocha North",
      "Aniocha-North",
      "Aniocha-South",
      "Bomadi",
      "Burutu",
      "Ethiope-East",
      "Ethiope-West",
      "Ika-North-East",
      "Ika-South",
      "Isoko-North",
      "Isoko-South",
      "Ndokwa-East",
      "Ndokwa-West",
      "Okpe",
      "Oshimili-North",
      "Oshimili-South",
      "Patani",
      "Sapele",
      "Udu",
      "Ughelli-North",
      "Ughelli-South",
      "Ukwuani",
      "Uvwie",
      "Warri South-West",
      "Warri North",
      "Warri South",
    ],
  },
  {
    code: "EB",
    name: "Ebonyi",
    lgas: [
      "Abakaliki",
      "Afikpo-North",
      "Afikpo South (Edda)",
      "Ebonyi",
      "Ezza-North",
      "Ezza-South",
      "Ikwo",
      "Ishielu",
      "Ivo",
      "Izzi",
      "Ohaukwu",
      "Onicha",
    ],
  },
  {
    code: "ED",
    name: "Edo",
    lgas: [
      "Akoko Edo",
      "Egor",
      "Esan-Central",
      "Esan-North-East",
      "Esan-South-East",
      "Esan-West",
      "Etsako-Central",
      "Etsako-East",
      "Etsako-West",
      "Igueben",
      "Ikpoba-Okha",
      "Oredo",
      "Orhionmwon",
      "Ovia-North-East",
      "Ovia-South-West",
      "Owan East",
      "Owan-West",
      "Uhunmwonde",
    ],
  },
  {
    code: "EK",
    name: "Ekiti",
    lgas: [
      "Ado-Ekiti",
      "Efon",
      "Ekiti-East",
      "Ekiti-South-West",
      "Ekiti-West",
      "Emure",
      "Gbonyin",
      "Ido-Osi",
      "Ijero",
      "Ikere",
      "Ikole",
      "Ilejemeje",
      "Irepodun Ifelodun",
      "Ise-Orun",
      "Moba",
      "Oye",
    ],
  },
  {
    code: "EN",
    name: "Enugu",
    lgas: [
      "Aninri",
      "Awgu",
      "Enugu-East",
      "Enugu-North",
      "Enugu-South",
      "Ezeagu",
      "Igbo-Etiti",
      "Igbo-Eze-North",
      "Igbo-Eze-South",
      "Isi-Uzo",
      "Nkanu-East",
      "Nkanu-West",
      "Nsukka",
      "Oji-River",
      "Udenu",
      "Udi",
      "Uzo-Uwani",
    ],
  },
  {
    code: "GO",
    name: "Gombe",
    lgas: [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shongom",
      "Yamaltu Deba",
    ],
  },
  {
    code: "IM",
    name: "Imo",
    lgas: [
      "Aboh-Mbaise",
      "Ahiazu-Mbaise",
      "Ehime-Mbano",
      "Ezinihitte",
      "Ideato-North",
      "Ideato-South",
      "Ihitte Uboma",
      "Ikeduru",
      "Isiala-Mbano",
      "Isu",
      "Mbaitoli",
      "Ngor-Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji-Egbema",
      "Okigwe",
      "Onuimo",
      "Orlu",
      "Orsu",
      "Oru-East",
      "Oru-West",
      "Owerri-Municipal",
      "Owerri-North",
      "Owerri-West",
    ],
  },
  {
    code: "JI",
    name: "Jigawa",
    lgas: [
      "Auyo",
      "Babura",
      "Biriniwa",
      "Birnin-Kudu",
      "Buji",
      "Dutse",
      "Gagarawa",
      "Garki",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin-Hausa",
      "Kaugama",
      "Kazaure",
      "Kiri kasama",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Ringim",
      "Roni",
      "Sule-Tankarkar",
      "Taura",
      "Yankwashi",
    ],
  },
  {
    code: "KD",
    name: "Kaduna",
    lgas: [
      "Birnin-Gwari",
      "Chikun",
      "Giwa",
      "Igabi",
      "Ikara",
      "Jaba",
      "Jema'A",
      "Kachia",
      "Kaduna-North",
      "Kaduna-South",
      "Kagarko",
      "Kajuru",
      "Kaura",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon-Gari",
      "Sanga",
      "Soba",
      "Zangon-Kataf",
      "Zaria",
    ],
  },
  {
    code: "KN",
    name: "Kano",
    lgas: [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawakin-Kudu",
      "Dawakin-Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garun-Mallam",
      "Gaya",
      "Gezawa",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano-Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin-Gado",
      "Rogo",
      "Shanono",
      "Sumaila",
      "Takai",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
      "Tudun-Wada",
      "Ungogo",
      "Warawa",
      "Wudil",
    ],
  },
  {
    code: "KT",
    name: "Katsina",
    lgas: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dan-Musa",
      "Dandume",
      "Danja",
      "Daura",
      "Dutsi",
      "Dutsin-Ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "Mai-Adua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango",
    ],
  },
  {
    code: "KE",
    name: "Kebbi",
    lgas: [
      "Aleiro",
      "Arewa-Dandi",
      "Argungu",
      "Augie",
      "Bagudo",
      "Birnin-Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko-Besse",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Wasagu/Danko",
      "Yauri",
      "Zuru",
    ],
  },
  {
    code: "KO",
    name: "Kogi",
    lgas: [
      "Adavi",
      "Ajaokuta",
      "Ankpa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igalamela-Odolu",
      "Ijumu",
      "Kabba Bunu",
      "Kogi",
      "Lokoja",
      "Mopa-Muro",
      "Ofu",
      "Ogori Magongo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Oyi",
      "Yagba-East",
      "Yagba-West",
    ],
  },
  {
    code: "KW",
    name: "Kwara",
    lgas: [
      "Asa",
      "Baruten",
      "Edu",
      "Ekiti (Araromi/Opin)",
      "Ilorin-East",
      "Ilorin-South",
      "Ilorin-West",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke-Ero",
      "Oyun",
      "Pategi",
    ],
  },
  {
    code: "LA",
    name: "Lagos",
    lgas: [
      "Agege",
      "Ajeromi-Ifelodun",
      "Alimosho",
      "Amuwo-Odofin",
      "Apapa",
      "Badagry",
      "Epe",
      "Eti-Osa",
      "Ibeju-Lekki",
      "Ifako-Ijaiye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos-Island",
      "Lagos-Mainland",
      "Mushin",
      "Ojo",
      "Oshodi-Isolo",
      "Shomolu",
      "Surulere",
      "Yewa-South",
    ],
  },
  {
    code: "NA",
    name: "Nassarawa",
    lgas: [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Kokona",
      "Lafia",
      "Nasarawa",
      "Nasarawa-Eggon",
      "Obi",
      "Wamba",
      "Toto",
    ],
  },
  {
    code: "NI",
    name: "Niger",
    lgas: [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Magama",
      "Mariga",
      "Mashegu",
      "Mokwa",
      "Moya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi",
    ],
  },
  {
    code: "OG",
    name: "Ogun",
    lgas: [
      "Abeokuta-North",
      "Abeokuta-South",
      "Ado-Odo Ota",
      "Ewekoro",
      "Ifo",
      "Ijebu-East",
      "Ijebu-North",
      "Ijebu-North-East",
      "Ijebu-Ode",
      "Ikenne",
      "Imeko-Afon",
      "Ipokia",
      "Obafemi-Owode",
      "Odeda",
      "Odogbolu",
      "Ogun-Waterside",
      "Remo-North",
      "Shagamu",
      "Yewa North",
    ],
  },
  {
    code: "ON",
    name: "Ondo",
    lgas: [
      "Akoko North-East",
      "Akoko North-West",
      "Akoko South-West",
      "Akoko South-East",
      "Akure-North",
      "Akure-South",
      "Ese-Odo",
      "Idanre",
      "Ifedore",
      "Ilaje",
      "Ile-Oluji-Okeigbo",
      "Irele",
      "Odigbo",
      "Okitipupa",
      "Ondo West",
      "Ondo-East",
      "Ose",
      "Owo",
    ],
  },
  {
    code: "OS",
    name: "Osun",
    lgas: [
      "Atakumosa West",
      "Atakumosa East",
      "Ayedaade",
      "Ayedire",
      "Boluwaduro",
      "Boripe",
      "Ede South",
      "Ede North",
      "Egbedore",
      "Ejigbo",
      "Ife North",
      "Ife South",
      "Ife-Central",
      "Ife-East",
      "Ifelodun",
      "Ila",
      "Ilesa-East",
      "Ilesa-West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo-Otin",
      "Ola Oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo",
    ],
  },
  {
    code: "OY",
    name: "Oyo",
    lgas: [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North-East",
      "Ibadan North-West",
      "Ibadan South-East",
      "Ibadan South-West",
      "Ibarapa-Central",
      "Ibarapa-East",
      "Ibarapa-North",
      "Ido",
      "Ifedayo",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogo-Oluwa",
      "Ogbomosho-North",
      "Ogbomosho-South",
      "Olorunsogo",
      "Oluyole",
      "Ona-Ara",
      "Orelope",
      "Ori-Ire",
      "Oyo-West",
      "Oyo-East",
      "Saki-East",
      "Saki-West",
      "Surulere",
    ],
  },
  {
    code: "PL",
    name: "Plateau",
    lgas: [
      "Barkin-Ladi",
      "Bassa",
      "Bokkos",
      "Jos-East",
      "Jos-North",
      "Jos-South",
      "Kanam",
      "Kanke",
      "Langtang-North",
      "Langtang-South",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Qua'an Pan",
      "Riyom",
      "Shendam",
      "Wase",
    ],
  },
  {
    code: "RI",
    name: "Rivers",
    lgas: [
      "Abua Odual",
      "Ahoada-East",
      "Ahoada-West",
      "Akuku Toru",
      "Andoni",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Eleme",
      "Emuoha",
      "Etche",
      "Gokana",
      "Ikwerre",
      "Khana",
      "Obio Akpor",
      "Ogba-Egbema-Ndoni",
      "Ogba Egbema Ndoni",
      "Ogu Bolo",
      "Okrika",
      "Omuma",
      "Opobo Nkoro",
      "Oyigbo",
      "Port-Harcourt",
      "Tai",
    ],
  },
  {
    code: "SO",
    name: "Sokoto",
    lgas: [
      "Binji",
      "Bodinga",
      "Dange-Shuni",
      "Gada",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto-North",
      "Sokoto-South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
    ],
  },
  {
    code: "TA",
    name: "Taraba",
    lgas: [
      "Ardo-Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim-Lamido",
      "Kurmi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing",
    ],
  },
  {
    code: "YO",
    name: "Yobe",
    lgas: [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari",
    ],
  },
  {
    code: "ZA",
    name: "Zamfara",
    lgas: [
      "Anka",
      "Bakura",
      "Birnin Magaji/Kiyaw",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Isa",
      "Kaura-Namoda",
      "Kiyawa",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talata-Mafara",
      "Tsafe",
      "Zurmi",
    ],
  },
];

// export default state;
export const state = [
  {
    name: "I have duplicate account",
  },
  {
    name: "I get too many notifications",
  },
  {
    name: "I found nothing interesting on sociamaket",
  },
  {
    name: "I was treated badly",
  },
  {
    name: "this is not what i bergained for",
  },
  {
    name: "sociamaket i believe can do better and you can start by improving on customer relationship",
  },
  {
    name: "Other reason",
  },
];
export const local = [
  {
    name: "Kiyawa",
  },
  {
    name: "Maradun",
  },
  {
    name: "Shinkafi",
  },
];
export const category = [
  // vehicles
  {
    name: "Vehicles",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297749/cars_gnuvyf.png",
    subCategory: [
      {
        name: "Vehicles",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297749/cars_gnuvyf.png",
      },
      {
        name: "Buses and Microbuses",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297749/buses_m6zvlx.png",
      },
      {
        name: "Heavy Equipment",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297748/heavy-equipment_dlmxu5.png",
      },
      {
        name: "Motorcycles and Scooters",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297748/moto_mbqjik.png",
      },
      {
        name: "Trucks and Trailers",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297748/trucks-and-trailers_ehjmiu.png",
      },
      {
        name: "Watercraft and Boats",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297748/watercrafts_rgr7ox.png",
      },
      {
        name: "Vehicle Parts and Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707297748/vehicle-parts-and-accessories_qykcfh.png",
      },
    ],
  },
  //   property
  {
    name: "Property",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/houses-and-apartments-for-sale_lgykts.png",
    subCategory: [
      {
        name: "Newly Built",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/new-builds_skxmc9.png",
      },
      {
        name: "Houses and Apartments for Rent",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/houses-and-apartments-for-rent_suahbb.png",
      },
      {
        name: "Houses and Apartments for Sale",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/houses-and-apartments-for-sale_lgykts.png",
      },
      {
        name: "Land and Plots for Sale",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/land-and-plots-for-sale_pev0pf.png",
      },
      {
        name: "Land and Plots for Rent",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/land-for-rent_aiwdaw.png",
      },
      {
        name: "Commercial Property for Rent",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298238/commercial-property-for-rent_le3w3s.png",
      },
      {
        name: "Commercial Property for Sale",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298289/commercial-property-for-sale_o2g19q.png",
      },
      {
        name: "Event Centers,Venues and Workstations",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298288/event-centers-and-venues_crf7un.png",
      },
      {
        name: "Short Let Property",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298287/short-let_higxoq.png",
      },
    ],
  },
  //   mobile phones and tablets
  {
    name: "Mobile Phones and Tablets",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298721/phones_ip8pun.png",
    subCategory: [
      {
        name: "Mobile Phones",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298721/phones_ip8pun.png",
      },
      {
        name: "Accessories for Mobile Phones and Tablets",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298721/accessories-for-mobile-and-tablet_lt1kbl.png",
      },

      {
        name: "Smart Watches and Trackers",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298721/watches_dcegwi.png",
      },
      {
        name: "Tablets",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298721/tablets_hoaoyr.png",
      },
    ],
  },

  // electronics
  {
    name: "Electronics",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298983/laptops_zfapfw.png",
    subCategory: [
      {
        name: "Accessories and Supplies for Electronics",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298984/accessories-and-supplies-electronics_y8y9cf.png",
      },
      {
        name: "Laptops and Computers",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298983/accessories-and-supplies-for-electronics_t2vq3v.png",
      },
      {
        name: "TV and DVD Equipment",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298982/tv_oonsxd.png",
      },
      {
        name: "Audio and Music Equipment",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298982/audio_srnnoh.png",
      },
      {
        name: "Computer Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298982/audio_srnnoh.png",
      },
      {
        name: "Computer Hardware",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707298960/computer-hardware_f5myuz.png",
      },
      {
        name: "Computer Monitors",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707299090/computer-monitors_d9bt7g.png",
      },
      {
        name: "Headphones",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707299089/headphones_ltivsw.png",
      },
      {
        name: "Printers and Scanners",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707299087/printers-and-scanners_edyndx.png",
      },
      {
        name: "Software",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707299084/software_pruoxl.png",
      },
      {
        name: "Video Game Consoles",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707299084/video-games_vyjqht.png",
      },
      {
        name: "Photo and Video Cameras",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707299087/cameras_yy3wy5.png",
      },
    ],
  },

  //   home furniture and appliances
  {
    name: "Home, Furniture and Appliances",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300077/furniture_mtuywt.png",
    subCategory: [
      {
        name: "Furniture",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300077/furniture_mtuywt.png",
      },

      {
        name: "Garden Supplies",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300076/garden_n5c7h6.png",
      },
      {
        name: "Home Appliances",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300072/home-accessories_ruvhzv.png",
      },
      {
        name: "Home Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300071/home-appliances_g4bz9b.png",
      },
      {
        name: "Kitchen Appliances",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300071/kitchen-appliances_uiry5j.png",
      },
      {
        name: "Kitchenware and Cookware",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300070/kitchen-and-dining_uoy71c.png",
      },

      {
        name: "Household Chemicals",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707300088/household-chemicals_itkjcw.png",
      },
    ],
  },

  //   fashion
  {
    name: "Fashion",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307051/clothing_pepacm.png",
    subCategory: [
      {
        name: "Clothing",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307051/clothing_pepacm.png",
      },
      {
        name: "Bags",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307055/bags_tyvlof.png",
      },
      {
        name: "Shoes",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307033/shoes_q9exqr.png",
      },
      {
        name: "Jewellery",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307257/jewelry_nb6ugw.png",
      },
      {
        name: "Watches",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307032/watches_hewjxo.png",
      },

      {
        name: "Wedding Wear and Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307032/wedding-wear_zoqfyp.png",
      },
    ],
  },
  // health and beauty
  {
    name: "Health and Beauty",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307421/bath-and-body_w1dm3y.png",
    subCategory: [
      {
        name: "Bath and Body",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307421/bath-and-body_w1dm3y.png",
      },
      {
        name: "Fragrance",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307419/fragrance_fpodpl.png",
      },
      {
        name: "Hair Beauty",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307418/hair-beauty_mzm16m.png",
      },
      {
        name: "Makeup",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307417/makeup_g4ps7j.png",
      },
      {
        name: "Sexual Wellness",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307417/makeup_g4ps7j.png",
      },
      {
        name: "Skin Care",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307413/skin-care_bbtsja.png",
      },
      {
        name: "Tobbaco Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307412/tobacco-accessories_r3s6fi.png",
      },
      {
        name: "Tools and Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307410/tools-and-accessories_gvfdcp.png",
      },
      {
        name: "Vitamins and Supplements",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307409/vitamins-and-supplements_jwmutb.png",
      },
    ],
  },

  // babies and kids
  {
    name: "Babies and Kids",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307835/babies-and-kids-accessories_losyu0.png",
    subCategory: [
      {
        name: "Babies, Kids and Accessories",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307835/babies-and-kids-accessories_losyu0.png",
      },
      {
        name: "Baby and Child Care",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307834/baby-and-child-care_v0i6t7.png",
      },
      {
        name: "Children's Clothing",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307832/children-clothing_efwztz.png",
      },
      {
        name: "Children's Furniture",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307832/children-clothing_efwztz.png",
      },
      {
        name: "Children's Gear and Safety",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307828/children-gear-and-safety_yf0oon.png",
      },
      {
        name: "Maternity and Pregnancy",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307764/maternity-and-pregnancy_dghhhh.png",
      },
      {
        name: "Prams and Strollers",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307763/prams-and-strollers_roztkj.png",
      },
      {
        name: "Toys",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307761/toys_xccs43.png",
      },
      {
        name: "Playground Equipment",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707307762/playground-equipment_a45f3x.png",
      },
    ],
  },

  // sports and outdoors
  {
    name: "Sports and Outdoors",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308299/sports-equipment_sohu4n.png",
    subCategory: [
      {
        name: "Arts and Crafts",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308317/arts_gnpiix.png",
      },
      {
        name: "Books and Games",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308317/arts_gnpiix.png",
      },
      {
        name: "Camping Gear",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308314/camping_wq9fkk.png",
      },
      {
        name: "CDs and DVDs",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308312/cds-and-dvds_tyd50n.png",
      },
      {
        name: "Musical Instruments and Gear",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308300/musical-Instruments-and-gear_k8xppd.png",
      },
      {
        name: "Sports Equipment",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308299/sports-equipment_sohu4n.png",
      },
    ],
  },

  // agriculture and food
  {
    name: "Agriculture and Food",
    avatar:
      "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308526/meals_zhlt2p.png",
    subCategory: [
      {
        name: "Farm Machinery and Equipment",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308547/equipment_dtpjwx.png",
      },
      {
        name: "Feeds, Supplements and Seeds",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308545/feeds_ursnvf.png",
      },
      {
        name: "Livestock and Poultry",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308544/livestock-and-poultry_ocxutk.png",
      },
      {
        name: "Meals and Drinks",
        avatar:
          "https://res.cloudinary.com/dcpbeiego/image/upload/v1707308526/meals_zhlt2p.png",
      },
    ],
  },
];
