on:
  push:
    branches:
      - main
name: 🚀 Deploy waitlist on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 🔨 Building Project
        run: |
          yarn
          yarn build

      - name: copying redirect files
        run: |
          cp -a ./_redirects ./dist/_redirects
          cp -a ./index.php ./dist/index.php
          cp -a ./.htaccess ./dist/.htaccess

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ~/
          local-dir: dist/
